server:
  http_listen_port: 9080 #云服务器需开放9080端口
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

#loki地址
clients:
  - url: http://123.123.123.123:3100/loki/api/v1/push


#我名词定义是 ”环境-服务-文件/容器“
scrape_configs:
- job_name: demo-servername-file
  static_configs:
  - targets:
    - localhost
    labels:
      client: demo                          #自定义变量 定义环境
      job: servername-file                  #变量定义类型
      __path__: /data/server/logs/*.log        #收集程序输出的日志


- job_name: dev-servername-file
  static_configs:
  - targets:
    - localhost
    labels:
      client: dev
      job: servername-file
      __path__: /data/server/logs/*.log